### ISSUE TITLE
new aria in html rule: aria-readonly / readonly attributes

### ISSUE THREAD

**Issue by scottaohara** [ThePacielloGroup/WAI-ARIA-Usage#13]
2 tests to implement checks for with expected results

https://w3c.github.io/html-aria/tests/readonly-test.html

**Comment by gezlemon** [comment]
Updated rules to allow aria-placeholder on input elements with type "date", "month", "week", "time", and "datetime-local"

Added rule to check for aria-readonly. Flags an error if used with a value of "false" along with a native readonly attribute. Otherwise flags a warning that aria-readonly is used with a native readonly attribute.

**Comment by scottaohara** [comment]
this one looks like it's returning some of the expected warnings / errors.

the 5 input types you mentioned are now flagging invalid use of aria-readonly=true and false when used with readonly

but the other 8 inputs on that test page aren't being flagged as invalid.
